#!/bin/bash

# Check if Python 3 is installed, if not, install it
if ! command -v python3 &> /dev/null; then
    echo "Python 3 is not installed. Installing Python 3..."
    sudo apt-get update
    sudo apt-get install -y python3
fi

# Uninstall Fabric
pip3 uninstall -y Fabric

# Install necessary dependencies
sudo apt-get install -y libffi-dev libssl-dev build-essential python3.4-dev libpython3-dev

# Install Python packages
pip3 install pyparsing appdirs setuptools==40.1.0 cryptography==2.8 bcrypt==3.1.7 PyNaCl==1.3.0 Fabric3==1.14.post1

echo "Setup completed."

